name: notify

on:
  workflow_run:
    workflows: [main]
    types:
      - completed

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.workflow_run.conclusion }}"
